require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


def shared_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  use_flipper!({ 'Flipper' => '0.74.0' })
end


target 'EmmaReactNativeExample' do 
  shared_pods  
end

target 'EmmaReactNativeExampleSwift' do
  shared_pods  
end

  post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
		end
	end
  end

target 'NotificationService' do
  pod 'eMMa', '~> 4.9.0' 
end

target 'NotificationServiceSwift' do
  pod 'eMMa', '~> 4.9.0'
end
